export const DUMMY_BOOKS = [
    {
        id: "1",
        title: "The Great Gatsby",
        userId: "1",
        author: "F. Scott Fitzgerald",
        isbn: "9780743273565",
        genre: "Classic",
        cover: "https://m.media-amazon.com/images/I/71UypkUjStL._AC_UF894,1000_QL80_.jpg",
        avgRating: 4.2,
        reviews: [
            {
                id: '13456',
                user: "John Doe",
                text: "A fantastic look at the Jazz Age and the American Dream.",
                rating: 4,
            },
            {
                id: '2342',
                user: "Jane Smith",
                text: "A timeless classic that explores deep themes of love and loss.",
                rating: 5,
            },
        ],
    },
    {
        id: "2",
        title: "To Kill a Mockingbird",
        userId: "2",
        author: "Harper Lee",
        isbn: "9780061120084",
        genre: "Historical Fiction",
        cover: "https://m.media-amazon.com/images/I/81A-mvlo+QL._AC_UF1000,1000_QL80_.jpg",
        avgRating: 4.8,
        reviews: [
            {
                id: '341',
                user: "Michael Johnson",
                text: "A deeply moving novel about race and morality in the South.",
                rating: 5,
            },
            {
                id: '342',
                user: "Emily Davis",
                text: "An eye-opening read that stays with you long after finishing.",
                rating: 5,
            },
        ],
    },
    {
        id: "3",
        title: "1984",
        userId: "3",
        author: "George Orwell",
        isbn: "9780451524935",
        genre: "Dystopian",
        cover: "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
        avgRating: 4.6,
        reviews: [
            {
                id: '145',
                user: "Alice Brown",
                text: "Chilling and thought-provoking. A must-read for any dystopian fan.",
                rating: 4,
            },
            {
                id: '223',
                user: "David Lee",
                text: "A brilliant work that shows the dangers of totalitarianism.",
                rating: 5,
            },
        ],
    },
    {
        id: "4",
        title: "Pride and Prejudice",
        userId: "4",
        author: "Jane Austen",
        isbn: "9780141439518",
        genre: "Romance",
        cover: "https://m.media-amazon.com/images/I/81WojUxbbFL._AC_UF894,1000_QL80_.jpg",
        avgRating: 4.4,
        reviews: [
            {
                id: '112',
                user: "Charlotte Wilson",
                text: "An exquisite romance with sharp wit and insightful commentary.",
                rating: 5,
            },
            {
                id: '13434',
                user: "Thomas Harris",
                text: "A delightful and timeless love story. Truly one of the best.",
                rating: 4,
            },
        ],
    },
    {
        id: "5",
        title: "The Catcher in the Rye",
        userId: "5",
        author: "J.D. Salinger",
        isbn: "9780316769488",
        genre: "Coming-of-Age",
        cover: "https://m.media-amazon.com/images/I/81OthjkJBuL._AC_UF1000,1000_QL80_.jpg",
        avgRating: 3.9,
        reviews: [
            {
                id: '534',
                user: "Sarah Walker",
                text: "A deep and introspective look into teenage angst and alienation.",
                rating: 4,
            }
        ],
    },
    {
        id: "6",
        title: "Moby-Dick",
        userId: "6",
        author: "Herman Melville",
        isbn: "9780142437247",
        genre: "Adventure",
        cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?crop=entropy&cs=tinysrgb&fit=max&w=400&h=400",
        avgRating: 4.0,
        reviews: [
        ],
    },
    {
        id: "7",
        title: "The Hobbit",
        userId: "7",
        author: "J.R.R. Tolkien",
        isbn: "9780547928227",
        genre: "Fantasy",
        cover: "https://m.media-amazon.com/images/I/91b0C2YNSrL._AC_UF1000,1000_QL80_.jpg",
        avgRating: 4.7,
        reviews: [
            {
                id: '234',
                user: "Peter King",
                text: "A brilliant and adventurous fantasy novel that captures the imagination.",
                rating: 5,
            },
            {
                id: '234234',
                user: "Anna Bell",
                text: "A delightful and easy-to-read fantasy story for all ages.",
                rating: 4,
            },
        ],
    },
];
